version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wedding-postgres
    environment:
      POSTGRES_DB: wedding_db
      POSTGRES_USER: wedding_user
      POSTGRES_PASSWORD: wedding_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wedding_user -d wedding_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local